### ISSUE TITLE
Nice to have branch releases/v1

### ISSUE THREAD

**Issue by ypresto** [strumwolf/delete-deployment-environment#3]
Currently example in README.md fails.
Also with the branch we can always use latest non-breaking change one. :)

**Comment by strumwolf** [comment]
Is it just a typo? Does `strumwolf/delete-deployment-environment@v1.01` work rather than `strumwolf/delete-deployment-environment@releases/v1`?

**Comment by strumwolf** [comment]
I updated the readme and created a `release/v1` branch. `uses: strumwolf/delete-deployment-environment@v1.1.0` should not give you any problems.

Thanks for the comments.
