### ISSUE TITLE
Failing to find Action

### ISSUE THREAD

**Issue by Chanonry** [strumwolf/delete-deployment-environment#6]
Getting:

Failed to resolve action download info. Error: Unable to resolve action `strumwolf/delete-deployment-environment@1.1.0`, unable to find version `1.1.0`

File is:

name: Deployment Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Application Environment
        required: true
        default: dev

      version:
        description: Deployed Version
        required: true
        default: 010

      region:
        description: Deployment Region
        required: true
        default: us-west-2

jobs:
  destroy_deployment:

    runs-on: ubuntu-20.04

    steps:
        - uses: strumwolf/delete-deployment-environment@1.1.0
          with:
            token: ${{ secrets.DEPLOYMENT_TOKEN }}
            environment: ${context.payload.inputs.environment}${context.payload.inputs.version}-${context.payload.inputs.region}

**Comment by Katsute** [comment]
Try changing it to `strumwolf/delete-deployment-environment@v1.1.0`.

**Comment by strumwolf** [comment]
Thanks Katsute for pointing out the typo.
