### ISSUE TITLE
feature request: delete environment protection rules

### ISSUE THREAD

**Issue by missedone** [strumwolf/delete-deployment-environment#8]
hi, 
first of all, thanks for the nice github actions, it helps alot for our CI/CD flow. we create test env for each PR, so we clean them up once PR merged/closed.
however, the environment protection rules still there, now that there's new api https://github.blog/changelog/2021-02-23-github-actions-environment-environment-protection-rules-and-deployment-reviewers-api/
would like to add option to delete it as well? 
Thanks

**Comment by strumwolf** [comment]
Yeah sure I can add that as an option. I'll have the deletion of the environment as the default and stick deleting the deployments and not the environment behind an input variable.

**Comment by strumwolf** [comment]
v2 is ready to go.

**Comment by missedone** [comment]
thanks for adding the support, but got error bolow

Error: Cannot find module '@actions/core'
Require stack:
- /workspace/_actions/strumwolf/delete-deployment-environment/v2.0.0/dist/execute.js
- /workspace/_actions/strumwolf/delete-deployment-environment/v2.0.0/dist/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/workspace/_actions/strumwolf/delete-deployment-environment/v2.0.0/dist/execute.js:32:27)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/workspace/_actions/strumwolf/delete-deployment-environment/v2.0.0/dist/execute.js',
    '/workspace/_actions/strumwolf/delete-deployment-environment/v2.0.0/dist/main.js'
  ]

**Comment by strumwolf** [comment]
Yeah, I just thought about that problem. I will fix.

**Comment by strumwolf** [comment]
Okay, try it again when you have change.

**Comment by missedone** [comment]
tried 2.0.1, different error:
> Found 1 deployments
deactivating deployments in environment pr269
deleting deployments in environment pr269
deleting environment pr269
Error: Resource not accessible by integration

**Comment by missedone** [comment]
ok it works after using the privileged token rather then the default `${{ github.token }}`

refer to the doc https://docs.github.com/en/rest/reference/repos#delete-an-environment
> You must authenticate using an access token with the repo scope to use this endpoint.
